// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/loanflow/v1/loanflow.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_api_loanflow_v1_loanflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_loanflow_v1_loanflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_api_loanflow_v1_loanflow_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_api_loanflow_v1_loanflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_loanflow_v1_loanflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_api_loanflow_v1_loanflow_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

var File_api_loanflow_v1_loanflow_proto protoreflect.FileDescriptor

const file_api_loanflow_v1_loanflow_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/loanflow/v1/loanflow.proto\x12\vloanflow.v1\"6\n" +
	"\rSubmitRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\")\n" +
	"\x0eSubmitResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId2[\n" +
	"\vLoanService\x12L\n" +
	"\x11SubmitApplication\x12\x1a.loanflow.v1.SubmitRequest\x1a\x1b.loanflow.v1.SubmitResponseB.Z,github.com/smashraid/pandora/api/loanflow/v1b\x06proto3"

var (
	file_api_loanflow_v1_loanflow_proto_rawDescOnce sync.Once
	file_api_loanflow_v1_loanflow_proto_rawDescData []byte
)

func file_api_loanflow_v1_loanflow_proto_rawDescGZIP() []byte {
	file_api_loanflow_v1_loanflow_proto_rawDescOnce.Do(func() {
		file_api_loanflow_v1_loanflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_loanflow_v1_loanflow_proto_rawDesc), len(file_api_loanflow_v1_loanflow_proto_rawDesc)))
	})
	return file_api_loanflow_v1_loanflow_proto_rawDescData
}

var file_api_loanflow_v1_loanflow_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_loanflow_v1_loanflow_proto_goTypes = []any{
	(*SubmitRequest)(nil),  // 0: loanflow.v1.SubmitRequest
	(*SubmitResponse)(nil), // 1: loanflow.v1.SubmitResponse
}
var file_api_loanflow_v1_loanflow_proto_depIdxs = []int32{
	0, // 0: loanflow.v1.LoanService.SubmitApplication:input_type -> loanflow.v1.SubmitRequest
	1, // 1: loanflow.v1.LoanService.SubmitApplication:output_type -> loanflow.v1.SubmitResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_loanflow_v1_loanflow_proto_init() }
func file_api_loanflow_v1_loanflow_proto_init() {
	if File_api_loanflow_v1_loanflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_loanflow_v1_loanflow_proto_rawDesc), len(file_api_loanflow_v1_loanflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_loanflow_v1_loanflow_proto_goTypes,
		DependencyIndexes: file_api_loanflow_v1_loanflow_proto_depIdxs,
		MessageInfos:      file_api_loanflow_v1_loanflow_proto_msgTypes,
	}.Build()
	File_api_loanflow_v1_loanflow_proto = out.File
	file_api_loanflow_v1_loanflow_proto_goTypes = nil
	file_api_loanflow_v1_loanflow_proto_depIdxs = nil
}
