package service_test

import (
	"context"
	"errors"
	"testing"
	"time"

	"github.com/smashraid/pandora/internal/adapters/outbound/memory"
	"github.com/smashraid/pandora/internal/domain"
	"github.com/smashraid/pandora/internal/service"
)

func setupService() (*service.LoanService, *memory.MemoryTaskRepository, *memory.MemoryEventBroker) {
	repo := memory.NewMemoryTaskRepository()
	broker := memory.NewMemoryEventBroker()
	svc := service.NewLoanService(repo, broker, broker)
	return svc, repo, broker
}

func TestLoanService_SubmitApplication(t *testing.T) {
	svc, repo, _ := setupService()
	ctx := context.Background()

	app := &domain.LoanApplication{
		ID:                   "app-test-001",
		ApplicantEmail:       "test@example.com",
		RequestedAmountCents: 1000000,
		Priority:             domain.PriorityHigh,
		CreatedAt:            time.Now().UTC(),
	}

	// 1. Submit application
	task, err := svc.SubmitApplication(ctx, app)
	if err != nil {
		t.Fatalf("expected no error submitting application, got: %v", err)
	}

	if task.TaskID == "" {
		t.Error("expected non-empty TaskID generated by service")
	}
	if task.ApplicationID != app.ID {
		t.Errorf("expected ApplicationID %s, got %s", app.ID, task.ApplicationID)
	}
	if task.Status != domain.TaskStatusPending {
		t.Errorf("expected initial status %s, got %s", domain.TaskStatusPending, task.Status)
	}

	// 2. Verify application saved in repo
	savedApp, err := repo.GetApplicationByID(ctx, app.ID)
	if err != nil {
		t.Fatalf("expected application to be saved in repository, got: %v", err)
	}
	if savedApp.ApplicantEmail != app.ApplicantEmail {
		t.Errorf("expected email %s, got %s", app.ApplicantEmail, savedApp.ApplicantEmail)
	}
}

func TestLoanService_GetTaskStatus(t *testing.T) {
	svc, _, _ := setupService()
	ctx := context.Background()

	app := &domain.LoanApplication{
		ID:                   "app-test-002",
		ApplicantEmail:       "status@example.com",
		RequestedAmountCents: 500000,
		Priority:             domain.PriorityStandard,
	}

	task, err := svc.SubmitApplication(ctx, app)
	if err != nil {
		t.Fatalf("failed to submit application: %v", err)
	}

	fetchedTask, err := svc.GetTaskStatus(ctx, task.TaskID)
	if err != nil {
		t.Fatalf("expected to fetch task status, got: %v", err)
	}

	if fetchedTask.TaskID != task.TaskID {
		t.Errorf("expected task ID %s, got %s", task.TaskID, fetchedTask.TaskID)
	}
}

func TestLoanService_CancelTask(t *testing.T) {
	svc, repo, _ := setupService()
	ctx := context.Background()

	app := &domain.LoanApplication{
		ID:                   "app-cancel-001",
		ApplicantEmail:       "cancel@example.com",
		RequestedAmountCents: 2000000,
		Priority:             domain.PriorityStandard,
	}

	task, err := svc.SubmitApplication(ctx, app)
	if err != nil {
		t.Fatalf("failed to submit application: %v", err)
	}

	// Cancel active task
	err = svc.CancelTask(ctx, task.TaskID, "user revoked request")
	if err != nil {
		t.Fatalf("expected task cancellation to succeed, got: %v", err)
	}

	cancelledTask, err := repo.GetTaskByID(ctx, task.TaskID)
	if err != nil {
		t.Fatalf("failed to get cancelled task: %v", err)
	}

	if cancelledTask.Status != domain.TaskStatusCancelled {
		t.Errorf("expected status %s, got %s", domain.TaskStatusCancelled, cancelledTask.Status)
	}

	// Attempting to cancel an already terminal task should fail
	err = svc.CancelTask(ctx, task.TaskID, "second cancel attempt")
	if !errors.Is(err, domain.ErrTaskAlreadyCompleted) {
		t.Errorf("expected domain.ErrTaskAlreadyCompleted when cancelling terminal task, got: %v", err)
	}
}

func TestLoanService_PipelineExecution(t *testing.T) {
	svc, _, _ := setupService()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	app := &domain.LoanApplication{
		ID:                   "app-pipeline-001",
		ApplicantEmail:       "pipeline@example.com",
		RequestedAmountCents: 1500000,
		Priority:             domain.PriorityHigh,
	}

	task, err := svc.SubmitApplication(ctx, app)
	if err != nil {
		t.Fatalf("failed to submit application: %v", err)
	}

	// Subscribe to execution progress events
	stream, err := svc.SubscribeTaskUpdates(ctx, task.TaskID)
	if err != nil {
		t.Fatalf("failed to subscribe to task updates: %v", err)
	}

	// Monitor progress updates streamed from background worker pipeline
	var lastProgress int32
	for {
		select {
		case update, ok := <-stream:
			if !ok {
				t.Fatal("stream closed before task completed")
			}
			if update.ProgressPercentage < lastProgress {
				t.Errorf("progress regressed from %d to %d", lastProgress, update.ProgressPercentage)
			}
			lastProgress = update.ProgressPercentage

			if update.Status == domain.TaskStatusCompleted {
				if update.ProgressPercentage != 100 {
					t.Errorf("expected 100%% progress on completion, got %d%%", update.ProgressPercentage)
				}
				return
			}
		case <-ctx.Done():
			t.Fatalf("timed out waiting for background pipeline execution to finish (last progress: %d%%)", lastProgress)
		}
	}
}
