apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  VALKEY_HOST: {{ .Values.config.valkeyHost | quote }}
  VALKEY_PORT: {{ .Values.config.valkeyPort | quote }}
  HTTP_PORT: {{ .Values.scheduler.httpPort | quote }}
  GRPC_PORT: {{ .Values.scheduler.grpcPort | quote }}