apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-scheduler
  labels:
    app.kubernetes.io/component: scheduler
spec:
  replicas: {{ .Values.scheduler.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/component: scheduler
    spec:
      containers:
        - name: scheduler
          image: "{{ .Values.image.repositoryPrefix }}-scheduler:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.scheduler.httpPort }}
            - name: grpc
              containerPort: {{ .Values.scheduler.grpcPort }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secret
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.scheduler.grpcPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.scheduler.grpcPort }}
            initialDelaySeconds: 10
            periodSeconds: 15